package problem_modelings.budget_constrained_modeling;

import algorithms_modeling.Cuckoo.CuckooModelingInterface;
import problem_modelings.modeling_types.BudgetConstrainedModelAbstract;

public class CuckooBudgetConstrainedModeling extends BudgetConstrainedModelAbstract implements CuckooModelingInterface {
}
