package problem_modelings.budget_constrained_modeling;

import problem_modelings.algorithms_modeling.CuckooModelingInterface;
import problem_modelings.modeling_types.BudgetConstrainedModelAbstract;

public class CuckooBudgetConstrainedModeling extends BudgetConstrainedModelAbstract implements CuckooModelingInterface {
}
