package problem_modelings.budget_constrained_modeling;

import algorithms_modeling.cuckoo.CuckooModelingInterface;
import problem_modelings.modeling_types.BudgetConstrainedModelAbstract;

public class CuckooBudgetConstrainedModeling extends BudgetConstrainedModelAbstract implements CuckooModelingInterface {
}
