package problem_modelings.budget_constrained_modeling;

import algorithms_modeling.SA.SAModelingInterface;
import problem_modelings.modeling_types.BudgetConstrainedModelAbstract;

public class SABudgetConstrainedModeling extends BudgetConstrainedModelAbstract implements SAModelingInterface {
}
