package problem_modelings.cost_optimization.model_specifications;

import base_algorithms.quantum_annealing.QAResultBaseInterface;

public class CostOptimizationModelingQAResult implements QAResultBaseInterface {
}
