package problem_modelings.cost_optimization.model_specifications;

import base_algorithms.simulated_annealing.SAResultBaseInterface;

public class CostOptimizationModelingSAResult implements SAResultBaseInterface {
}
